version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "the-mace"
    assignees:
      - "the-mace"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      # Group dev dependencies together
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
        update-types:
          - "minor"
          - "patch"
      # Group runtime dependencies together
      runtime-dependencies:
        patterns:
          - "httpx"
          - "python-dotenv"
          - "click"
          - "rich"
        update-types:
          - "minor"
          - "patch"
    # Separate major version updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "the-mace"
    assignees:
      - "the-mace"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"
