name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        I'm trying to do X, but there's no way to Y...

        Current workaround (if any):
        ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        ```python
        # Example of how you'd like to use the feature
        from kubera import KuberaClient

        client = KuberaClient()
        result = client.new_feature()
        ```
      render: python
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or features have you considered?
      placeholder: |
        - Alternative approach 1: ...
        - Alternative approach 2: ...

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the library would this affect?
      options:
        - Client API (library)
        - Command-line interface (CLI)
        - Authentication
        - Error handling
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change to existing code?
      options:
        - "No - backward compatible"
        - "Yes - would break existing code"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other information that would help understand the feature:
        - Links to similar features in other libraries
        - API documentation references
        - Screenshots or mockups
      placeholder: Additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Implementation
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a clear use case and proposed solution
          required: true
